Repository KIET7UKE/Hacktoberfest-2K22, pull requests merged in 2022-10, with the labels that each got.

#29 Added Bored Bot
  JavaScript Projects/27 - Bored Bot/hand.png
  JavaScript Projects/27 - Bored Bot/index.html
  JavaScript Projects/27 - Bored Bot/main.js
  JavaScript Projects/27 - Bored Bot/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#91 Create StringAnagramsList.java
  DSA/StringAnagramsList.java
Labels: duplicate, invalid

#103 Added Digit Frequency and Array Reversal Code
  DSA/HackerRank/Array_Reversal.c
  DSA/HackerRank/Digit_Frequency.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktober-accepted

#154 Added linear linked list summation code
  DSA/C PROGRAM/linear_linked_list.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktober-accepted, hacktoberfest-approved

#153 Created a new file happy_number.cpp
  DSA/HAPPY NUMBER/happy_number.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktober-accepted, hacktoberfest-approved
